from collections.abc import Iterator
from datetime import datetime

from arrow import Arrow
from ics.grammar.parse import Container

class Event:
    name: str | None
    description: str | None
    extra: Container
    def __init__(self) -> None: ...
    @property
    def begin(self) -> Arrow | None: ...
    @begin.setter
    def begin(self, value: datetime | Arrow | None) -> None: ...
    @property
    def end(self) -> Arrow | None: ...
    @end.setter
    def end(self, value: datetime | Arrow | None) -> None: ...
    def make_all_day(self) -> None: ...

class Calendar:
    events: set[Event]
    def __init__(self) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
