class ContentLine:
    def __init__(
        self, name: str, params: dict[str, list[str]] = ..., value: str = ""
    ) -> None: ...
    @classmethod
    def parse(cls, line: str) -> ContentLine: ...

class Container(list[ContentLine]): ...
